Repository HyperloopUPV-H8/software, pull requests merged in 2024-06, with the labels that each got.

#144 [control-station] Boards page first window
  common-front/lib/components/Connections/Connections.module.scss
  control-station/index.html
  control-station/src/App.module.scss
  control-station/src/assets/svg/battery-filled.svg
  control-station/src/assets/svg/thermometer-field.svg
  control-station/src/assets/svg/thermometer-filled.svg
  control-station/src/assets/svg/thunder-filled.svg
  control-station/src/components/BarIndicator/BarIndicator.module.scss
  control-station/src/components/BarIndicator/BarIndicator.tsx
  control-station/src/components/BatteryConnector/BatteryConnector.module.scss
  control-station/src/components/BatteryConnector/BatteryConnector.tsx
  control-station/src/components/BatteryPack/BatteryPack.module.scss
  control-station/src/components/BatteryPack/BatteryPack.tsx
  control-station/src/components/GaugeTag/GaugeTag.module.scss
  control-station/src/components/GaugeTag/GaugeTag.tsx
  control-station/src/components/GaugeTag/TextData/TextData.module.scss
  control-station/src/components/IndicatorStack/IndicatorStack.module.scss
  control-station/src/components/IndicatorStack/IndicatorStack.tsx
  control-station/src/components/Pagination/PaginationItem/PaginationItem.module.scss
  control-station/src/components/Sidebar/Sidebar.module.scss
  control-station/src/components/Sidebar/SidebarItem/SidebarItem.module.scss
  control-station/src/components/StateIndicator/StateIndicator.module.scss
  control-station/src/components/StateIndicator/StateIndicator.tsx
  control-station/src/components/Window/Window.module.scss
  control-station/src/pages/PageWrapper/PageWrapper.module.scss
  control-station/src/pages/VehiclePage/Boards/BMSL/BMSL.module.scss
  control-station/src/pages/VehiclePage/Boards/BMSL/BMSL.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryInfo/BatteryInfo.module.scss
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryInfo/BatteryInfo.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryPack/BatteryPack.module.scss
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryPack/BatteryPack.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCU.module.scss
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCU.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCUBatteries.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCUGeneralInfo.tsx
  control-station/src/pages/VehiclePage/Boards/VCU/VCU.module.scss
  control-station/src/pages/VehiclePage/Boards/VCU/VCU.tsx
  control-station/src/pages/VehiclePage/Boards/VCU/VCUBrakesInfo.tsx
  control-station/src/pages/VehiclePage/Boards/VCU/VCUPositionInfo.tsx
  control-station/src/pages/VehiclePage/BoardsPage/BoardsPage.module.scss
  control-station/src/pages/VehiclePage/BoardsPage/BoardsPage.tsx
  control-station/src/pages/VehiclePage/VehiclePage.module.scss
  control-station/src/pages/VehiclePage/VehiclePage.tsx
  control-station/src/state.ts
  control-station/src/styles/fonts.scss
Labels: Task, Frontend

#145 [control-station] store optimisation
  common-front/lib/selectors/OBCCU.ts
  common-front/lib/store/measurementsStore.ts
  control-station/src/components/BarIndicator/BarIndicator.tsx
  control-station/src/components/IndicatorStack/IndicatorStack.module.scss
  control-station/src/components/StateIndicator/StateIndicator.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryPack/BatteryPack.module.scss
  control-station/src/pages/VehiclePage/Boards/OBCCU/BatteryPack/BatteryPack.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCUBatteries.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCUGeneralInfo.tsx
  control-station/src/pages/VehiclePage/BoardsPage/BoardsPage.tsx
Labels: Frontend, Enhancement

#146 [control-station] Boards Page
  common-front/lib/selectors/BMSL.ts
  common-front/lib/selectors/VCU.ts
  control-station/package-lock.json
  control-station/src/App.module.scss
  control-station/src/assets/svg/break-contracted.svg
  control-station/src/assets/svg/break-extended.svg
  control-station/src/assets/svg/vehicle-track.svg
  control-station/src/components/BarIndicator/BarIndicator.module.scss
  control-station/src/components/BarIndicator/BarIndicator.tsx
  control-station/src/components/BreakVisualizer/BreakVisualizer.module.scss
  control-station/src/components/BreakVisualizer/BreakVisualizer.tsx
  control-station/src/components/GaugeTag/GaugeTag.module.scss
  control-station/src/components/GaugeTag/GaugeTag.tsx
  control-station/src/components/GaugeTag/TextData/TextData.module.scss
  control-station/src/components/StateIndicator/StateIndicator.module.scss
  control-station/src/components/StateIndicator/StateIndicator.tsx
  control-station/src/components/VehiclePosition/VehiclePosition.tsx
  control-station/src/pages/PageWrapper/PageWrapper.module.scss
  control-station/src/pages/VehiclePage/Boards/BMSL/BMSL.tsx
  control-station/src/pages/VehiclePage/Boards/OBCCU/OBCCUGeneralInfo.tsx
  control-station/src/pages/VehiclePage/Boards/VCU/VCU.module.scss
  control-station/src/pages/VehiclePage/Boards/VCU/VCUBrakesInfo.tsx
  control-station/src/pages/VehiclePage/Boards/VCU/VCUPositionInfo.tsx
  control-station/src/pages/VehiclePage/BoardsPage/BoardsPage.module.scss
  control-station/src/pages/VehiclePage/BoardsPage/BoardsPage.tsx
  control-station/src/state.ts
Labels: Task, Feature

#147 [control-station] Remove unused code
  control-station/src/components/BarTag/Bar/Bar.scss
  control-station/src/components/BarTag/Bar/Bar.tsx
  control-station/src/components/BarTag/Bar/BoolBar/BoolBar.module.scss
  control-station/src/components/BarTag/Bar/BoolBar/BoolBar.tsx
  control-station/src/components/BarTag/Bar/RangeBar/RangeBar.module.scss
  control-station/src/components/BarTag/Bar/RangeBar/RangeBar.tsx
  control-station/src/components/BarTag/BarTag.module.scss
  control-station/src/components/BarTag/BarTag.tsx
  control-station/src/components/IconTag/IconTag.module.scss
  control-station/src/components/IconTag/IconTag.tsx
  control-station/src/components/ImageTag/ImageTag.module.scss
  control-station/src/components/ImageTag/ImageTag.tsx
  control-station/src/components/StateOverlay/StateOverlay.module.scss
  control-station/src/components/StateOverlay/StateOverlay.tsx
  control-station/src/components/StateView/Badge/Badge.module.scss
  control-station/src/components/StateView/Badge/Badge.tsx
  control-station/src/components/StateView/StateView.module.scss
  control-station/src/components/StateView/StateView.tsx
  control-station/src/components/ValueData/ValueData.module.scss
  control-station/src/components/ValueData/ValueData.tsx
  control-station/src/components/ValueDataTag/ValueDataTag.tsx
  control-station/src/components/ValueWithUnits/ValueWithUnits.module.scss
  control-station/src/components/ValueWithUnits/ValueWithUnits.tsx
  control-station/src/components/VehiclePosition/VehiclePosition.tsx
Labels: Task, Enhancement

#149 Backend memory and performance optimizations
  .gitignore
  backend/cmd/main.go
  backend/pkg/broker/topics/message/message_test.go
  backend/pkg/logger/data/logger.go
  backend/pkg/logger/file/csv.go
  backend/pkg/logger/logger_test.go
  backend/pkg/logger/order/logger.go
  backend/pkg/logger/protection/logger.go
  backend/pkg/logger/state/logger.go
  backend/pkg/transport/packet/protection/decoder.go
  backend/pkg/transport/packet/protection/kind.go
  backend/pkg/transport/packet/protection/packet.go
  backend/pkg/transport/presentation/decoder_test.go
  backend/pkg/transport/session/sniffer.go
  common-front/lib/models/Message.ts
  ethernet-view/src/components/MessagesContainer/Messages/MessageView/ProtectionMessageView/ProtectionView/ProtectionView.tsx
Labels: Enhancement
